### ISSUE TITLE
API to query accounts by public key

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#162]
For people who import keys into wallet need a way to find set of accounts this keys accessing to.
Usually it will be only one account, and this makes it easy to retrieve that account by public key.

Technical details:
  - need to add additional index in the storage to be able to retrieve this information
  - RPC query, account/<public key> -> returns list of <account_id>

**Comment by frol** [comment]
As per the discussion in https://github.com/nearprotocol/near-explorer/issues/236#issuecomment-607703486, we should implement this in Explorer backend since it is relatively cheap (just save into the DB table what we already have fetched).

The DB layout is simple:

* account_id (string) -- that is `receiver_id` from the transaction
* public_key (string) -- that is `public_key` from `AddKey` actions
* access_key_type (string) -- `FunctionCall` or `FullAccess`

The primary key has to be a compound of `account_id` and `public_key` columns (just mark both of those as `primary` and sequelize will do the rest).

Notes:

* A single transaction can have none or many AddKey actions, and all should be added, so a single `account_id` can have many records on the access_keys table
* The same public_key can potentially be used by several `account_id` (it is not recommended from the security point of view, nevertheless it is still possible)

**Comment by frol** [comment]
Oh, I finally recalled what was the quirk, that is the fact that access keys can also be removed.

@vgrichina @ilblackdragon What is the expected behavior for the case when the key was added and then removed? (extra: what if added, removed, but then added again?) Is it fine to just ignore this fact and let Wallet to check the current list of active access keys for the account_id via RPC?

Solutions:

* keep track of the block timestamps where the last AddKey and the last DeleteKey happened (use two separate columns, so then the active status will be determined by the comparison of those timestamps)
* have a separate table for the deleted access keys with the timestamp of the block where the deletion happened

**Comment by ilblackdragon** [comment]
It's fine to just return current keys.

If key will be added back later (same as if it gets added in the first place to some other account) - wallets should run process from time to time to discover new accounts that this key gives access now. 

Otherwise, if user wants it right away, they can go through importing key process again.

**Comment by frol** [comment]
@vgrichina @ilblackdragon We landed the implementation to production, but I don't want to do the full re-sync since the new testnet will do the hard-fork soon.

Query: 

```sql
SELECT * FROM access_keys LIMIT 2
```

Response:
```js
[
    {
      account_id: 'frol.test',
      public_key: 'ed25519:32p7ReBuqGxptafddDt4uJvbrmuERwLMQZkXxuv9mjeH',
      access_key_type: 'FullAccess'
    },
    {
      account_id: 'frol.test',
      public_key: 'ed25519:7bAPjLc3MUy6snnf6z1Z17KVRudguyT1ML1hN6SsgN5x',
      access_key_type: 'FullAccess'
    }
]
```
