### ISSUE TITLE
Block list page issues

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-explorer#43]
Going to https://explorer.nearprotocol.com/blocks:
 - changing number of blocks per page doesn't change anything. 
 - there are no pages also to scroll.
 - can not click on the on block number / hash to go to the block details
 - block date is still "invalid date"

**Comment by robin-thomas** [comment]
@ilblackdragon 
1. That's correct. Need to first get a stable render.com connection working, so that I can work well with real data.
2. As for pagination, I'm in discussion with Jake (as we have to change the pagination shown in the design mocks. Will need some discussion with the UX team on this)

3 and 4 are already fixed by PR: https://github.com/nearprotocol/near-explorer/pull/41
