### ISSUE TITLE
Add contract info to Account Detail page

### ISSUE THREAD

**Issue by kcole16** [nearprotocol/near-explorer#92]
## Story

As a user, I want to view the details of a contract deployed on an account, so I learn about the contract's behavior and determine whether or not to trust the contract.

## Acceptance Criteria

- [ ] Indicator if a contract is deployed to an account
- [ ] If contract, the following is displayed
  - [ ] Last updated timestamp (when the contract was last redeployed), links to TX detail page of the most recent deployContract TX
  - [ ] Locked status (False, if the contract has any FullAccessKeys)
- [ ] Clicking on the creator's name/address redirects to the account detail page
- [ ] Mobile ok
- [ ] Tested

## Assets

- [Designs](https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=42%3A1694)

## Notes
**Locked status**
- If account has any FullAccessKey, status is `False`
- If account has no FullAccessKey, status is `True`

**Comment by frol** [comment]
Note: The Account Detail Page #90 shares quite a number of items, so it can be reused.

**Comment by corwinharrell** [comment]
@kcole16 since there are initial designs for this new page, I would love to get an initial impression from the explorer team to help me get some context around some of the decision making here. That would be help to ease me into a better understanding of some of the explorer components and would be helpful for me to then take that feedback and move forward with any additional design work that may be necessary to get to where we want to be with this.

If anyone who is able to provide feedback on the original designs in Figma, that would be great so I can see that feedback in context. Enter comment mode by opening the Figma file provided in the issue description and pressing `C`

**Comment by corwinharrell** [comment]
Also, one thing that would be extremely helpful for initiating data-centric design efforts like this would be a plain-text file that represented a dummy contract table that contained dummy data for each element of the contract. This file could be used to provide life-like data to be used in design exploration, and would help to ensure from the start that we are designing around the content and that we can make sure that everything from the issue checklist, including all possible states, is included in the raw data of this file. Thoughts?

**Comment by kcole16** [comment]
@corwinharrell Added comments to the Figma, and created some dummy data here: https://docs.google.com/spreadsheets/d/1_0SS8vNt06JS6itoKQpo6nrWNNLYoRxgv9OssQya_IM/edit?usp=sharing

**Comment by corwinharrell** [comment]
@kcole16 @frol @icerove I've updated the [design link](https://www.figma.com/file/jS1bjIiVxoEPNOYeXwddjH/NEAR-Explorer?node-id=42%3A1694) with the latest updates to the new account page with contract information. Feel free to leave feedback if you have any. Press `C` in Figma to comment.

Tried to make the changes within the constraints of the current explorer UI without adding too many new elements and while re-using as much as possible. I did leave several things alone that were present in the initial designs that Jake had created since I have little context for some of the decisions made at that point in time, so if there's anything here that we think needs to change just mention it and I can do that asap. It seemed like a lot of the acceptance criteria were already present in the designs, but that it just needed to be changes slightly since we just wanted to display the contract info as a part of the account page.

**Comment by corwinharrell** [comment]
@kcole16 one thing I noticed is that a couple data points present in the initial designs are not mentioned in the acceptance criteria for this issue, so I opted to ommit them:

1. Contract balance
2. # of Contract Transactions

Let me know if you'd like to reintroduce those and that should be easy enough.

**Comment by kcole16** [comment]
> @kcole16 one thing I noticed is that a couple data points present in the initial designs are not mentioned in the acceptance criteria for this issue, so I opted to ommit them:

@corwinharrell Contract balance is the same as the account balance, so good to omit that! And users can figure out the number of contract transactions by filtering, so should be covered there as well.

**Comment by icerove** [comment]
@kcole16 how could we know whether the contract has access key or not?

**Comment by frol** [comment]
@icerove Use `query` API:

https://github.com/near/near-api-js/blob/092d6477854906e51a59a406f0587b1174e4d02b/src.ts/providers/json-rpc-provider.ts#L47

`["access_key/<account_id>", ""]` (https://docs.nearprotocol.com/docs/interaction/rpc#access_keyaccount_id)

**Comment by frol** [comment]
@icerove to clarify, there is `nearcore-query` WAMP endpoint, so frontend should query RPC through Explorer backend (this is the design we follow here to avoid inconsistency).

**Comment by icerove** [comment]
@frol  as you can see in https://docs.nearprotocol.com/docs/interaction/rpc#access_keyaccount_id, there is a list of access key, which one should be used to see whether permission is fullaccess?

**Comment by frol** [comment]
@icerove All of them. There should be no key with FullAccess permission on the list to mark the contract being locked.

**Comment by icerove** [comment]
@frol still be a problem.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/33007476/77217197-d4479880-6add-11ea-9301-d568cf83b604.png">
the second access_key in the keys array, its permission is an Action object, how could this one to say whether FullAcess or not?

**Comment by bowenwang1996** [comment]
@icerove if it is an object it means that it is not a full access key (as you can see the permission is `FunctionCall`, which means it can only be used to call functions in a specific contract).

**Comment by frol** [comment]
@icerove See https://github.com/nearprotocol/nearcore/pull/2285. `FullAccess` and `FunctionCall` are two (the only two) types of access keys. It is just unfortunate that the value is a string in the first case (the mentioned PR should fix this inconsistency, see the examples in the PR description).
